### ISSUE TITLE
3.9.2 Recordings are missing from GUI

### ISSUE THREAD

**Issue by Mike1082** [pducharme/UniFi-Video-Controller#75]
I believe something changed in the recording path with this version. Since updating today, all of my recordings have disappeared from the GUI (they all still exist in their respective folders).

My container path for "Recording Path" has been set to "/var/lib/unifi-video/videos", but in the System Configuration GUI, it is now appearing as "/usr/lib/unifi-video/data/videos" (which is not listed in the dockerfile). If I try to change this path in the GUI, I get an error:

```
Validation Failed
/var/lib/unifi-video/videos path is not accessible.
Please correct permissions or ownership and try again.
```
In the logs, I see lots of errors referencing this path:

`java.io.FileNotFoundException: /usr/lib/unifi-video/data/videos/9d23058c-3d53-3b5e-b07d-f290f5fe136e/2018/01/29/1517254547165_1517254549165_1517252347798_6166117.mp4 (No such file or directory)`

**Comment by Mike1082** [comment]
FWIW, I tried rolling back using the 3.9.0 tag, but it appears that the firmware that the camera was updated to is not supported in 3.9.0

**Comment by fryfrog** [comment]
Can you show me your `docker run` command?

**Comment by fryfrog** [comment]
My mapping is currently `-v /data/unifi-video/videos:/var/lib/unifi-video/videos`, but it also worked when I had `-v /data/unifi-video/videos:/usr/lib/unifi-video/data/videos` on the new image.

I did recently adjust the volume definition to go to the real place, but I'm not sure why that would cause this problem.

**Comment by fryfrog** [comment]
There is also a `perms.txt` file somewhere on your volume, if you remove it the docker will fix permissions at start up.

**Comment by Mike1082** [comment]
@fryfrog I am using unRaid, so the template is handling the run command.
That said, these are the details:

![image](https://user-images.githubusercontent.com/5722156/36755662-e13a043c-1bda-11e8-9394-381022b43fc6.png)

When I apply the template to start the container, this is the generated command:

`docker run -d --name="UniFi-Video" --net="bridge" --privileged="true" -e TZ="America/New_York" -e HOST_OS="unRAID" -p 6666:6666/tcp -p 7080:7080/tcp -p 7442:7442/tcp -p 7443:7443/tcp -p 7445:7445/tcp -p 7446:7446/tcp -p 7447:7447/tcp -v "/mnt/cache/appdata/unifi-video-logs/":"/var/log/unifi-video":rw -v "/mnt/cache/appdata/unifi-video/":"/var/lib/unifi-video":rw -v "/mnt/user/securitycameras/":"/var/lib/unifi-video/videos":rw pducharme/unifi-video-controller`

**Comment by fryfrog** [comment]
Where does it get the Dockerfile? The `:latest` one removed the 1st one which is the logs path and still has the 2nd one and the 3rd one still points at `/usr/lib/unifi-video/data/videos`.

If you flip to `:testing`, the logs one should be gone and it switches the 2nd one to be what you have there.

I don't use unRaid, I'm not entirely sure what is going on?

**Comment by fryfrog** [comment]
I don't see why it'd *fix* it, but maybe just remove the `logs` volume?

**Comment by fryfrog** [comment]
Also, to roll back to 3.9.0 you'd have to downgrade the firmware on your cameras manually.

**Comment by Mike1082** [comment]
Sorry, I was not showing "Advanced" in the container config screen.
If I had been, you would see the "Docker HUB URL" field, which has the following:

`https://registry.hub.docker.com/u/pducharme/unifi-video-controller/`

I will try removing the volume mapping for the Logs volume.

**Comment by Mike1082** [comment]
Basically, unRaid gives you a GUI to configure Docker containers, instead of using the CLI. I can resort to CLI if I need to.

**Comment by fryfrog** [comment]
Can you refresh it somehow? The logs volume is gone from both `latest` and `testing`. And for some reason, the README.md and Dockerfile is from the last thing to build, which was `testing`.

**Comment by fryfrog** [comment]
I've pushed master -> release and made a 3.9.2 tag. It should build in 5-15 minutes. Then refresh your template somehow and see if it helps? :/

**Comment by Mike1082** [comment]
Ok, I was able to fix this. In case anyone else updates their container using unRaid, follow these steps:

Go to the Community Applications plugin (or "Apps" tab).
Search for "unifi video"
Click the button shown below to reinstall the container using default values:
![image](https://user-images.githubusercontent.com/5722156/36757416-7b883cc6-1bdf-11e8-811f-8d6c498c70d6.png)
Note that the container path for videos is now `/videos`: (template must have been recently updated)
![image](https://user-images.githubusercontent.com/5722156/36757468-a7b01bb6-1bdf-11e8-8f20-bfccb85a7c6c.png)
Set your host path to the correct volume
Click Apply to update/run the container
Login to UVC, and go to Settings > System Configuration
Update the recording path to `/videos`
![image](https://user-images.githubusercontent.com/5722156/36757649-249ae9ee-1be0-11e8-858e-422b6dfa9815.png)
Under "Tools", check "Restore Recordings" and click "Analyze":
![image](https://user-images.githubusercontent.com/5722156/36757697-439aab9a-1be0-11e8-8eca-06826db5dfa6.png)
After this I got a popup indicating that my recordings had been restored:
![image](https://user-images.githubusercontent.com/5722156/36757733-564face0-1be0-11e8-8861-361ed11e0f79.png)
After going back to view Recordings, I was pleased to see they had all become visible again.

Hopefully this helps someone else. Thank you so much @fryfrog for the assist!

**Comment by Mike1082** [comment]
One last note: The logs volume is still present in the unRaid template, so I left it in place.

**Comment by pducharme** [comment]
We will update the Unraid docker template soon.  This is not in the same repo than the docker itself.

**Comment by fryfrog** [comment]
Hey @Mike1082, I think I'd re-fiddle your setup a little. I don't think `/videos` is a good place for it inside the container because you'll have to remember it every time. The default is `/var/lib/unifi-video/videos` and should be fine to map into.

I've also put up a commit to fix up the template.

**Comment by Mike1082** [comment]
Thanks, I will leave it as is for now, then check the template for updates before updating the container again.

**Comment by fryfrog** [comment]
It is actually totally fine to leave your videos in `/videos` on the inside, just remember you did that if you ever re-install or something. :)

**Comment by Mike1082** [comment]
Technically I didn't change it at all.. I just went by how the template was configured 👍
